READ_DEC MACRO
READ_AGAIN:
	MOV AH,8		; READ CHAR FROM KEYBOARD SAVE ASCII CODE IN AL
	INT 21H			; CALL DOS ROUTINE
	CMP AL, 'D'		; IF IS NEW LINE GOTO END
	JE QUIT
	CMP AL, '0' 	
	JL READ_AGAIN	; IF AL < '0' THEN READ_AGAIN
	CMP AL, '9' 	
	JG READ_AGAIN	; SAME IF AL > '9'
VALID_DECIMAL:		; ELSE IS A VALID DECIMAL PRINT IT OUT
	MOV DL,AL 		
	MOV AH,2 		; PRINT	
	INT 21H
QUIT:
ENDM